version: '3.5'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'  # notice initial waiting
    volumes:
      - .:/app
    #ports:
    #  - 8008:8000
    expose:
      - 8000
    #environment:
    #  - DATABASE_URL=postgresql://fastapi:fastapi@db:5432/fastapi
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    #environment:
    #  - POSTGRES_USER=fastapi
    #  - POSTGRES_PASSWORD=fastapi
    #  - POSTGRES_DB=fastapi
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    #environment:
    #  - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
    #  - PGADMIN_DEFAULT_PASSWORD=admin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data: